name: gelir_gider_uygulamasi
description: "Gelir Gider Takip Uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  get: ^4.6.6

  # Paketler güncel
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  google_sign_in: ^6.2.1
  http: ^1.1.0
  app_links: ^6.3.0
  url_launcher: ^6.2.4
  
  google_fonts: ^6.1.0
  animated_bottom_navigation_bar: ^1.3.1
  ansicolor: ^2.0.3
  csslib: ^1.0.0
  html: ^0.15.4

  postgres: ^3.0.0
  supabase_flutter: ^2.3.0
  
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  uuid: ^4.3.3
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

dependency_overrides:
  intl: 0.20.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/kizilay.png
    - assets/images/logo.png
    - assets/images/arkaplan.jpg
    - assets/images/google_logo.png
    - assets/images/icon.png
    - assets/images/splash_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/icon.png"
  remove_alpha_ios: true